import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "../context/appContext";
import { SocketProvider } from "../context/socketContext";

export const metadata: Metadata = {
  title: "Chat-app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <SocketProvider>{children}</SocketProvider>
        </AppProvider>
      </body>
    </html>
  );
}
